// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gewfafaswmsfqoteauqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdld2ZhZmFzd21zZnFvdGVhdXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4OTk4NzQsImV4cCI6MjA3MzQ3NTg3NH0.ZQ1fR5X9u7gEHaVN3PnQ-DCsWmzlyAJWIn1Tf4-9etY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});